# Información de la aplicación
application:
  # Autor de la aplicación
  author: ${AUTHOR}
  # Descripción de la aplicación
  description: ${DESCRIPTION}
  security:
    jwt:
      # Tiempo de expiración del JWT
      expiration: ${SECURITY_JWT_EXPIRATION}
      # Clave secreta para la firma del JWT
      secret-key: ${SECURITY_JWT_SECRET_KEY}
    public:
      # Rutas públicas que no requieren autenticación
      routes: ${SECURITY_PUBLIC_ROUTES}
  # Título de la aplicación
  title: ${TITLE}
  # Versión de la aplicación
  version: ${VERSION}

# Configuración del servidor
server:
  # Puerto en el que la aplicación escucha
  port: ${PORT}
  tomcat:
    # Tiempo de espera para las conexiones de Tomcat
    connection-timeout: ${SERVER_TOMCAT_TIMEOUT}

# Configuración de Spring
spring:
  application:
    # Nombre de la aplicación
    name: ${APP_NAME}
  data:
    mongodb:
      # URI de conexión a MongoDB
      uri: ${DATA_CONNECTION_METHOD}://${DATA_SOURCE_USERNAME}:${DATA_SOURCE_PASSWORD}@${DATA_SOURCE_DOMAIN}/${DATA_SOURCE_DB}?${DATA_PARAMS}
    redis:
      # Configuración de la base de datos Redis
      database: ${CACHE_DB}
      host: ${CACHE_HOST}
      lettuce:
        pool:
          # Configuración de la conexión en pool para Redis
          max-active: ${CACHE_LETTUCE_POOL_MAX_ACTIVE}
          max-idle: ${CACHE_LETTUCE_POOL_MAX_IDLE}
          max-wait: ${CACHE_LETTUCE_POOL_MAX_WAIT}
          min-idle: ${CACHE_LETTUCE_POOL_MIN_IDLE}
      # Configuración de la autenticación en Redis
      password: ${CACHE_PASSWORD}
      port: ${CACHE_PORT}
      timeout: ${CACHE_TIMEOUT}
      username: ${CACHE_USERNAME}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    default-model-expand-depth: 1
    default-model-rendering: example
    display-operation-id: false
    display-request-duration: true
    doc-expansion: list
    enabled: true
    path: /
    url: /v3/api-docs