package peppertech.crm.api.Tasks.Model.DTO;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.List;

/**
 * Data Transfer Object for a Kanban Column (phase).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ColumnDTO implements Serializable {

    @Schema(description = "Unique identifier of the column, generated by the database.",
            example = "64a1f9b5e4b0f23d4c8a7e25", hidden = true)
    private String id;

    @Schema(description = "Name of the column. Must be between 3 and 50 characters.",
            example = "In Progress")
    private String name;

    @Schema(description = "Optional description of the column, up to 300 characters.",
            example = "Tasks currently in progress")
    private String description;

    @Schema(description = "Color of the column in hex format.",
            example = "#1A73E8")
    private String color;

    @Schema(description = "ID of the board this column belongs to.",
            example = "64a1f9b5e4b0f23d4c8a7e20")
    private String board;

    @Schema(description = "List of card (task) IDs associated with this column.",
            example = "[\"64a1f9b5e4b0f23d4c8a7e30\", \"64a1f9b5e4b0f23d4c8a7e31\"]")
    private List<String> cards;
}
