package peppertech.crm.api.Tasks.Model.DTO;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object for a Subtask within a Kanban Card.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SubtaskDTO {

    @Schema(description = "Unique identifier of the subtask, generated by the database.", example = "64a1f9b5e4b0f23d4c8a7e50", hidden = true)
    private String id;

    @Schema(description = "Title of the subtask. Must be between 3 and 100 characters.", example = "Write unit tests")
    private String title;

    @Schema(description = "Date and time when the subtask was created.", example = "2025-06-09T14:20:30.123Z")
    private String createdAt;

    @Schema(description = "Date when the subtask was closed or completed.", example = "2025-06-15")
    private String closedDate;

    @Schema(description = "Priority level of the subtask.", example = "HIGH")
    private String priority;

    @Schema(description = "ID of the user assigned to this subtask.", example = "64a1f9b5e4b0f23d4c8a7e60")
    private String assignedTo;

    @Schema(description = "ID of the parent card to which this subtask belongs.", example = "64a1f9b5e4b0f23d4c8a7e40")
    private String card;
}